Repository acm-ucr/r-tools, pull requests merged in 2023-10, with the labels that each got.

#15 Add input component
  src/components/Input.jsx
Labels: GENERAL, READY FOR REVIEW

#16 5 landing
  src/Assets/RToolsLogo.svg
  src/components/home/Landing.jsx
Labels: CHANGES REQUESTED

#17 3 header
  src/components/Header.jsx
Labels: CHANGES REQUESTED

#26 Create code view
  package-lock.json
  package.json
  src/components/CodeView.jsx
Labels: EDITOR, READY FOR REVIEW

#24 11 boolean toolbar
  src/components/math/BoolToolBar.jsx
Labels: READY FOR REVIEW
