Repository acm-ucr/r-tools, pull requests merged in 2023-12, with the labels that each got.

#105 Change Icons
  src/data/navigation.js
Labels: READY FOR REVIEW

#107 Implement Bogo Sort
  src/app/algorithm/bogo-sort/page.js
  src/data/navigation.js
  src/util/sort/bogoSort.js
Labels: ALGORITHM

#108 Step Backward
  src/components/algorithm/AlgorithmWrapper.jsx
  src/components/algorithm/ArrayToolbar.jsx
Labels: GENERAL

#106 56 merge sort page
  src/app/algorithm/merge-sort/page.js
  src/util/sort/mergeSort.js
Labels: READY FOR REVIEW

#115 Implement Karnaugh mapping
  src/app/math/boolean-simplifier/page.js
  src/components/math/TruthTable.jsx
  src/util/math/KMap.js
  src/util/math/TruthTable.js
Labels: ALGORITHM, READY FOR REVIEW

#104 added LATEX page in nav
  src/data/navigation.js
Labels: READY FOR REVIEW
