Repository acm-ucr/r-tools, pull requests merged in 2023-11, with the labels that each got.

#31 progress on navbar
  src/app/layout.js
  src/components/Card.jsx
  src/components/Input.jsx
  src/components/Navigation.jsx
  src/data/navigation.js
Labels: GENERAL, DO NOT MERGE

#30 Map home page
  src/app/page.js
  src/components/Card.jsx
  src/components/Input.jsx
  src/components/Navigation.jsx
  src/components/home/Landing.jsx
  src/data/navigation.js
Labels: HOME

#20 Create Footer component
  src/components/Footer.jsx
Labels: GENERAL, CHANGES REQUESTED

#43 Implement binary tree component
  package-lock.json
  package.json
  src/components/algorithm/BinaryTree.jsx
Labels: ALGORITHM

#46 Created the toolbar
  src/components/algorithm/ArrayToolbar.jsx
Labels: READY FOR REVIEW

#47 Add no search results prompt
  src/app/page.js
Labels: HOME

#45 22 equations
  src/components/math/Equations.jsx
Labels: READY FOR REVIEW

#48 Bool Wrapper
  src/components/Header.jsx
  src/components/math/BoolToolBar.jsx
  src/components/math/BoolWrapper.jsx
Labels: READY FOR REVIEW

#50 No Nav Result Message
  src/components/Navigation.jsx
Labels: GENERAL, READY FOR REVIEW

#62 34 set min page h to screen
  src/app/layout.js
Labels: READY FOR REVIEW

#63 Truth Table Component and Page
  src/app/math/truth-tables/page.js
  src/components/math/Equations.jsx
  src/components/math/TruthTable.jsx
Labels: MATH

#78 fix home search
  src/data/navigation.js
Labels: HOME

#76 fix python of selection sort page
  src/util/sort/selectionSort.js
Labels: ALGORITHM, READY FOR REVIEW

#77 Quick Sort Page
  src/app/algorithm/quick-sort/page.js
  src/util/sort/quickSort.js
Labels: ALGORITHM, READY FOR REVIEW

#75 Bubble Sort Page
  src/app/algorithm/bubble-sort/page.js
  src/util/sort/bubbleSort.js
Labels: ALGORITHM, READY FOR REVIEW

#85 add styling to algorithm wrapper
  src/components/algorithm/AlgorithmWrapper.jsx
  src/components/charts/BarChart.jsx
Labels: ALGORITHM, READY FOR REVIEW

#88 Implement heap sort page
  src/app/algorithm/heaps/page.js
  src/util/sort/heap.js
Labels: ALGORITHM, READY FOR REVIEW
