Repository acm-ucr/r-tools, pull requests merged in 2024-02, with the labels that each got.

#186 init data for floyd warshall
  src/util/graph/floyd-warshall.js
Labels: READY FOR REVIEW

#193 Fixed PNG download
  src/util/editor/graphFunctions.js
Labels: READY FOR REVIEW, BUG FIX

#196 removed state machine
  src/app/graph/state-machine/page.js
  src/data/navigation.js
Labels: READY FOR REVIEW, BUG FIX

#198 Created Prim's page
  src/app/graph/prims/page.js
  src/data/navigation.js
Labels: READY FOR REVIEW, GRAPH

#203 fixed issue
  src/util/sort/selectionSort.js
Labels: READY FOR REVIEW

#205 created kruskals page
  src/app/graph/kruskals/page.js
  src/data/navigation.js
  src/util/graph/kruskals.js
Labels: READY FOR REVIEW

#206 Implemented Bellman-Ford Algorithm
  src/app/graph/bellmen-ford/page.js
  src/util/graph/bellmen-ford.js
Labels: READY FOR REVIEW

#216 Implemented functioning replay button
  src/components/Graph/GraphAlgorithm.jsx
Labels: READY FOR REVIEW

#207 added weighted directed indicators
  src/components/Graph/GraphAlgorithm.jsx
Labels: READY FOR REVIEW, GRAPH

#215 init data for dfs
  src/util/graph/dfs.js
Labels: ALGORITHM, DO NOT MERGE, GRAPH

#214 Prim's Algorithm Initialized Data
  src/app/graph/prims/page.js
  src/util/graph/prims.js
Labels: READY FOR REVIEW

#208 Added prop to Graph Algo
  src/components/Graph/GraphAlgorithm.jsx
Labels: ALGORITHM, READY FOR REVIEW
