Repository acm-ucr/r-tools, pull requests merged in 2024-03, with the labels that each got.

#227 add graph toolbar
  src/components/Graph/GraphAlgorithm.jsx
  src/components/Graph/GraphToolbar.jsx
Labels: GENERAL, READY FOR REVIEW

#222 Lillian/single color key
  src/components/Graph/ColorKey.jsx
Labels: READY FOR REVIEW

#219 Set play to false on generate
  src/components/algorithm/AlgorithmWrapper.jsx
Labels: ALGORITHM, READY FOR REVIEW, BUG FIX

#221 Add directed check
  src/components/Graph/GraphAlgorithm.jsx
Labels: READY FOR REVIEW

#223 added in initial table for kruskals
  src/util/graph/kruskals.js
Labels: READY FOR REVIEW

#220 DFS algorithm
  src/app/graph/dfs/page.js
  src/util/graph/dfs.js
Labels: ALGORITHM, READY FOR REVIEW

#230 Adjusted syntax highlight
  .idea/.gitignore
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/modules.xml
  .idea/r-tools.iml
  .idea/vcs.xml
  package-lock.json
  package.json
  src/components/CodeView.jsx
Labels: READY FOR REVIEW, BUG FIX

#232 Added Prim's Algorithm
  src/util/graph/prims.js
Labels: READY FOR REVIEW

#197 bfs alg
  src/app/graph/bellmen-ford/page.js
  src/app/graph/bfs/page.js
  src/app/graph/dfs/page.js
  src/app/graph/dijkstra/page.js
  src/app/graph/floyd-warshall/page.js
  src/app/graph/kruskals/page.js
  src/app/graph/prims/page.js
  src/components/Graph/GraphAlgorithm.jsx
  src/util/graph/bfs.js
Labels: CHANGES REQUESTED, GRAPH

#226 current state of Floyd Warshall
  src/util/graph/floyd-warshall.js
Labels: DO NOT MERGE

#224 Merge Pages
  src/app/graph/[algorithm]/page.js
  src/app/graph/bellmen-ford/page.js
  src/app/graph/bfs/page.js
  src/app/graph/dfs/page.js
  src/app/graph/dijkstra/page.js
  src/app/graph/floyd-warshall/page.js
  src/app/graph/kruskals/page.js
  src/app/graph/prims/page.js
  src/app/math/boolean-simplifier/page.js
  src/components/Graph/ColorKey.jsx
  src/components/Graph/EdgeEntry.jsx
  src/components/Graph/Graph.jsx
  src/components/Graph/GraphAlgorithm.jsx
  src/components/Graph/GraphEditor.jsx
  src/components/Graph/GraphIndications.jsx
  src/components/Graph/GraphToolbar.jsx
  src/data/graphPage.js
  src/data/navigation.js
  src/util/editor/graphFunctions.js
  src/util/graph/bellman-ford.js
  src/util/graph/bfs.js
  src/util/graph/dfs.js
  src/util/graph/dijkstra.js
  src/util/graph/floyd-warshall.js
  src/util/graph/kruskals.js
  src/util/graph/prims.js
  src/util/sort/visualize.js
Labels: READY FOR REVIEW

#240 404 page
  src/Assets/Error.svg
  src/app/not-found.js
Labels: READY FOR REVIEW
