Repository acm-ucr/r-tools, pull requests merged in 2024-01, with the labels that each got.

#153 Table border color fixed
  src/components/Table.jsx
Labels: READY FOR REVIEW

#155 bfs setup
  src/app/graph/bfs/page.js
  src/data/navigation.js
  src/util/graph/bfs.js
Labels: CHANGES REQUESTED

#157 Updated Selection Sort example code
  src/util/sort/selectionSort.js
Labels: READY FOR REVIEW

#160 Fixed default symbols bug
  src/app/math/truth-tables/page.js
Labels: READY FOR REVIEW

#167 Clear to Div
  src/components/Input.jsx
Labels: READY FOR REVIEW

#164 upload button
  src/components/Graph/GraphEditor.jsx
  src/components/Upload.jsx
Labels: READY FOR REVIEW

#163 Fix Code Examples for Bubble Sort
  src/util/sort/bubbleSort.js
  src/util/sort/selectionSort.js
Labels: ALGORITHM, CHANGES REQUESTED

#169 setup Floyd Warshall
  src/app/graph/floyd-warshall/page.js
  src/data/navigation.js
  src/util/graph/floyd-warshall.js
Labels: READY FOR REVIEW

#159 58 insertion sort page
  src/app/algorithm/insertion-sort/page.js
  src/util/sort/insertionSort.js
Labels: READY FOR REVIEW

#161 Negative Edge Toast
  src/components/Graph/GraphAlgorithm.jsx
Labels: READY FOR REVIEW, GRAPH

#165 Fixed/updated quick sort code
  src/util/sort/quickSort.js
Labels: READY FOR REVIEW

#173 Created Bellmen Ford Page
  src/app/graph/bellmen-ford/page.js
  src/data/navigation.js
  src/util/graph/bellmen-ford.js
Labels: READY FOR REVIEW

#174 113 shell sort
  src/app/algorithm/shell-sort/page.js
  src/util/sort/shellSort.js
Labels: READY FOR REVIEW

#175 dfs page
  src/app/graph/dfs/page.js
  src/data/navigation.js
  src/util/graph/dfs.js
Labels: ALGORITHM, READY FOR REVIEW, GRAPH

#176 Lillian/add duration in button
  src/components/Button.jsx
Labels: READY FOR REVIEW

#182 Added ActionButton
  src/components/ActionButton.jsx
  src/components/algorithm/ArrayToolbar.jsx
Labels: READY FOR REVIEW

#183 Weighted check
  src/app/graph/bfs/page.js
  src/app/graph/dijkstra/page.js
  src/app/graph/floyd-warshall/page.js
  src/components/Graph/GraphAlgorithm.jsx
Labels: READY FOR REVIEW, GRAPH

#184 Initialized data for Bellman Ford
  src/app/graph/bellmen-ford/page.js
  src/data/navigation.js
  src/util/graph/bellmen-ford.js
Labels: CHANGES REQUESTED

#185 Lillian/icondata
  src/data/icon.js
Labels: CHANGES REQUESTED
